[build-system]
requires = ["scikit-build-core", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "deviceaccess"
version = "3.3.2"
dependencies = ["numpy"]
description = "Python bindings for the ChimeraTK's deviceaccess library"
long_description = "The package provides binding for the ChimeraTK's deviceaccess library"
requires-python = ">=3.8"
readme = "README.md"
license = {file = "LICENSE"}

classifiers = [
"Topic :: Software Development :: Libraries :: Python Modules",
"Development Status :: 5 - Production/Stable",
"License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
"Intended Audience :: Developers",
"Programming Language :: Python :: 3",
"Programming Language :: Python :: 3.8",
"Programming Language :: Python :: 3.9",
"Programming Language :: Python :: 3.10",
"Programming Language :: Python :: 3.11",
"Programming Language :: Python :: 3.12",
"Programming Language :: Python :: 3.13",
"Programming Language :: Python :: Implementation :: CPython",
"Topic :: Scientific/Engineering"
]

[project.urls]
Homepage = "https://github.com/ChimeraTK/DeviceAccess-PythonBindings"
Documentation = "https://chimeratk.github.io/ChimeraTK-DeviceAccess-PythonBindings/head/html/"
Repository = "https://github.com/ChimeraTK/DeviceAccess-PythonBindings"

[tool.scikit-build]
# Protect the configuration against future changes in scikit-build-core
minimum-version = "0.4"

# Setuptools-style build caching in a local directory
build-dir = "build/{wheel_tag}"

# Build stable ABI wheels for CPython 3.12+
wheel.py-api = "cp312"

[tool.cibuildwheel]
before-all = "bash pre_build_manylinux.sh"
skip = "cp36-* cp37-* *-musllinux* pp* *-win32"
manylinux-x86_64-image = "manylinux_2_28"
manylinux-i686-image = "manylinux2_2_28"
manylinux-aarch64-image = "manylinux2_2_28"

# Necessary to see build output from the actual compilation
build-verbosity = 1

## Run pytest to ensure that the package was correctly built

#test-command = "python3 -m unittest discover tests"

